version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: cargo
    directory: "/firmware"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: "/hs-probe-bsp"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
